---
- name: Org-CV setup - https://titan-c.gitlab.io/org-cv.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Configuring org-cv...'
      - '--------------------------------------------------------------------'

- name: Copy org-cv.el to ~/.emacs.d/config.
  debug:
    msg:
      - '....................................................................'
      - 'Copying org-cv.el ...'
      - '....................................................................'

- name: Download org-cv.el file.
  get_url:
    url: https://is.gd/skZ4lP
    dest: /tmp/org-cv.el
  when: not ansible_check_mode

- name: Copy org-cv.el to each user .emacs.d/config folder.
  copy:
    src: /tmp/org-cv.el
    dest: "/home/{{ item }}/.emacs.d/config/org-cv.el"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u=rwx,g=r,o=r
  with_items: "{{ unified }}"
  become: true
  when:
    - not ansible_check_mode
    - unified is not variable_empty
    - item.item_name is not defined
    - not item == 'root'

- name: Copy org-cv.el to root .config folder.
  copy:
    src: /tmp/org-cv.el
    dest: /root/.emacs.d/config/org-cv.el
  with_items: "{{ unified }}"
  become: true
  when:
    - not ansible_check_mode
    - unified is not variable_empty
    - item.item_name is not defined
    - item == 'root'

- name: Copy org-cv.el to each user .emacs.d/config folder using item_name.
  copy:
    src: /tmp/monitors.xml
    dest: "/home/{{ item.item_name }}/.emacs.d/config/org-cv.el"
    owner: "{{ item.item_name }}"
    group: "{{ item.item_name }}"
    mode: u=rwx,g=r,o=r
  with_items: "{{ unified }}"
  become: true
  when:
    - not ansible_check_mode
    - unified is not variable_empty
    - item.item_name is defined
    - not item.item_name == 'root'

- name: Copy org-cv.el to root .emacs.d/config folder using item_name.
  copy:
    src: /tmp/org-cv.el
    dest: /root/.emacs.d/config/org-cv.el
  with_items: "{{ unified }}"
  become: true
  when:
    - not ansible_check_mode
    - unified is not variable_empty
    - item.item_name is defined
    - item.item_name == 'root'

- name: Cleanup /tmp/org-cv.el file.
  file:
    path: /tmp/org-cv.el
    state: absent
