- *~/.bashrc*

 - Adds the **changes** bash alias to quickly visualize repositories that were
   modified.

 - Adds the **runit** bash alias to quickly run an Ansible playbook.

 - Adds the **gic** bash alias to quickly make a git commit and push (lazy
   lazy villain).

- gnome

 - Sets the dock to include the launchers:

  - emacs

  - firefox.

  - libre-office writer.

  - nautilus

  - rhythmbox

  - terminal.

- nautilus

 - Adds the following folder bookmarks:

  - little-lab

  - repos

- virt

 - Adds each user to the following groups:

  - libvirt

  - libvirt-qemu

  - kvm
